### ISSUE TITLE
复现结果所需的超参数设置

### ISSUE THREAD

**Issue by Nikol-coder** [liuxiyang641/HVFormer#2]
作者，您好。
![图片](https://github.com/user-attachments/assets/a0af9003-7789-4b0b-ab79-12d4c8d7a24e)
![图片](https://github.com/user-attachments/assets/98f41f65-ab21-4468-a483-949a5404a1b3)

目前复现出来的结果，在F1分数上面还是低了2个点，只能达到81点几，想请教作者您，论文中最优结果所需的各种超参数是怎么设置的，目前还是以您提供的bash文件中的参数来跑的实验
![图片](https://github.com/user-attachments/assets/34613931-b134-473b-8f3c-aaa604677283)

**Comment by liuxiyang641** [comment]
你好，代码里的超参应该就是最好的结果。我们的超参大部分都和MKGFormer方法保持一致。
论文中的结果是运行多次的平均值，我们没有固定随机种子。你可以尝试多跑几次看看效果。

**Comment by Nikol-coder** [comment]
好的，非常感谢！！！



国科大+林昕奎
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuxiyang641/HVFormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月2日(星期五) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuxiyang641/HVFormer] 复现结果所需的超参数设置 (Issue #2)





 
你好，代码里的超参应该就是最好的结果。我们的超参大部分都和MKGFormer方法保持一致。
 论文中的结果是运行多次的平均值，我们没有固定随机种子。你可以尝试多跑几次看看效果。
